n = input('Digite algo: ')
print('O tipo primitivo é: ', type(n))
print('Só tem espaço: ', n.isnumeric())
print('È numérico: ', n.isnumeric())
print('È alfabético: ', n.isalpha())
print('È alfanumérico: ', n.isalnum())
print('È maisculo: ', n.isupper())
print('È minusculo: ', n.islower())
print('È capitalizada: ', n.istitle())